server {
    listen 80;

    server_name localhost;

    location = / {
        rewrite ^ /personalportalen/ last;
    }

    location = /personalportalen {
        return 301 /personalportalen/;
    }

    location /personalportalen/ {
        alias /usr/share/nginx/html/personalportalen/;
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        proxy_pass http://yarp-gateway:8080/;
    }
}