server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    # fix för utan slash
    location = /personalportalen {
        return 301 /personalportalen/;
    }

    # frontend
    location /personalportalen/ {
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        proxy_pass http://yarp-gateway:8080/;
    }
}